import {
  PartRequest,
  SavedAddress,
  ProcurementActivity,
  PortalNotification,
} from "@/types/portal";

export const SAVED_ADDRESSES: SavedAddress[] = [
  {
    id: "addr-01",
    label: "SP Motors Auckland Central (Main Workshop)",
    recipientName: "James Wilson (Workshop Reception)",
    businessName: "SP Motors Ltd",
    streetAddress: "34 Great South Road",
    suburb: "Penrose",
    city: "Auckland",
    postalCode: "1061",
    phone: "+64 9 525 8890",
    isDefault: true,
  },
  {
    id: "addr-02",
    label: "SP Motors North Shore Branch (Service Hub)",
    recipientName: "Mark Henderson (Parts Dept)",
    businessName: "SP Motors North Shore Ltd",
    streetAddress: "12 Barrys Point Road",
    suburb: "Takapuna",
    city: "Auckland",
    postalCode: "0622",
    phone: "+64 9 489 1234",
    isDefault: false,
  },
  {
    id: "addr-03",
    label: "SP Motors Christchurch Facility",
    recipientName: "Craig Watson",
    businessName: "SP Motors South Island",
    streetAddress: "88 Blenheim Road",
    suburb: "Riccarton",
    city: "Christchurch",
    postalCode: "8011",
    phone: "+64 3 348 7720",
    isDefault: false,
  },
];

export const INITIAL_REQUESTS: PartRequest[] = [
  {
    id: "req-128",
    requestNumber: "AutoHub-P-128",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "GDH201-0012845",
      registration: "MTB842",
      engine: "1GD-FTV (2.8L Turbo Diesel)",
      variant: "DX / Long Wheelbase",
      transmission: "6-Speed Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm",
      partNumber: "48069-26150",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Customer vehicle in hoist bay 2. Bushing torn and ball joint has excessive lateral play. Urgent dispatch requested.",
      photos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80",
      ],
      documents: ["Fitment_Verification_Hiace_2019.pdf"],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-08",
    status: "Quoted",
    quotedValue: 485.0,
    actionRequired: "Review & approve quote to proceed to fulfillment",
    actionType: "review_quote",
    quotation: {
      id: "quote-128",
      requestId: "req-128",
      version: 1,
      estimatedTransitDays: 5,
      itemDescription: "OEM Toyota Front Lower Suspension Arm (LH) with integrated high-durability silent bush and pre-greased ball joint.",
      oemNumber: "48069-26150",
      quantity: 1,
      unitPrice: 376.96,
      subtotal: 376.96,
      airFreightCost: 85, seaFreightCost: 45,
      freightNote: "Single flat freight value entered manually by Autohub staff",
      gstAmount: 63.04,
      totalAmount: 485.0,
      currency: "NZD",
      validUntil: "2026-09-12T18:00:00Z",
      termsAccepted: false,
      supplierLocation: "Autohub Nagoya Hub, Japan",
      notes: "Genuine Toyota factory sealed packaging. Backed by 12-month Autohub Trade Warranty. Pre-dispatch inspection passed.",
      quotePhotos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
      ],
    },
    messages: [],
  },
  {
    id: "req-125",
    requestNumber: "AutoHub-P-125",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "TRH200-0089122",
      registration: "NLE591",
      engine: "1TR-FE (2.0L Petrol)",
      variant: "GL High Roof",
      transmission: "Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm Assembly with Bushing & Ball Joint",
      partNumber: "48069-26140",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Replacement required for WOF reinspection this Friday.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-07",
    status: "Awaiting Payment",
    quotedValue: 485.0,
    actionRequired: "Settle invoice via Bank Transfer or Card",
    actionType: "pay_now",
    quotation: {
      id: "quote-125",
      requestId: "req-125",
      version: 1,
      estimatedTransitDays: 5,
      itemDescription: "Genuine Toyota Left Lower Arm Sub-Assembly with bushing and joint.",
      oemNumber: "48069-26140",
      quantity: 1,
      unitPrice: 376.96,
      subtotal: 376.96,
      airFreightCost: 85, seaFreightCost: 45,
      freightNote: "Single flat freight value entered manually by Autohub staff",
      gstAmount: 63.04,
      totalAmount: 485.0,
      currency: "NZD",
      validUntil: "2026-09-15T18:00:00Z",
      termsAccepted: true,
      supplierLocation: "Autohub Logistics Center, Nagoya",
    },
    quoteAcceptance: {
      acceptedAt: "2026-09-08 14:15 NZST",
      acceptedBy: "James Wilson",
      userRole: "Service Manager",
      termsAccepted: true,
      vehicleVerified: true,
      partVerified: true,
      addressVerified: true,
      freightCost: 85, selectedFreightType: "Air",
    },
    payment: {
      id: "pay-125",
      requestId: "req-125",
      invoiceNumber: "INV-2026-00892",
      amount: 485.0,
      currency: "NZD",
      status: "Unpaid",
      paymentReference: "AutoHub-P-125 / INV-00892",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
        swiftBic: "ANZBNZ22",
      },
      dueDate: "2026-09-14",
    },
    messages: [],
  },
  {
    id: "req-119",
    requestNumber: "AutoHub-P-119",
    vehicle: {
      make: "Mazda",
      model: "CX-5",
      year: 2021,
      vin: "KF2P-304910",
      registration: "PRT104",
      engine: "SH-VPTS 2.2L SkyActiv-D",
      variant: "Takami / AWD",
      transmission: "6-Speed Automatic",
      driveConfig: "AWD",
    },
    part: {
      name: "Front Headlamp (LED Projector RHS)",
      partNumber: "KB8B-51-031K",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Accident repair. LED signature ring and leveling motor must be intact with uncracked tabs.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[1],
    dateSubmitted: "2026-09-05",
    status: "Awaiting Payment",
    quotedValue: 650.0,
    actionRequired: "Settle invoice via Bank Transfer or Card",
    actionType: "pay_now",
    quotation: {
      id: "quote-119",
      requestId: "req-119",
      version: 1,
      estimatedTransitDays: 5,
      itemDescription: "Mazda OEM Adaptive LED Headlight Unit (Right Hand Side).",
      oemNumber: "KB8B-51-031K",
      quantity: 1,
      unitPrice: 515.22,
      subtotal: 515.22,
      airFreightCost: 90, seaFreightCost: 50,
      freightNote: "Single flat freight value entered manually by Autohub staff",
      gstAmount: 84.78,
      totalAmount: 650.0,
      currency: "NZD",
      validUntil: "2026-09-10T18:00:00Z",
      termsAccepted: true,
      supplierLocation: "Hiroshima, Japan",
    },
    payment: {
      id: "pay-119",
      requestId: "req-119",
      invoiceNumber: "INV-2026-00781",
      amount: 650.0,
      currency: "NZD",
      status: "Unpaid",
      paymentReference: "AutoHub-P-119",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
        swiftBic: "ANZBNZ22",
      },
      dueDate: "2026-09-10",
    },
    messages: [],
  },
  {
    id: "req-142",
    requestNumber: "AutoHub-P-142",
    vehicle: {
      make: "Toyota",
      model: "Hilux GR Sport",
      year: 2023,
      vin: "MR0HA3CD600129",
      registration: "RUG920",
      engine: "1GD-FTV High Output",
      variant: "GR Sport Widebody",
      transmission: "Automatic",
      driveConfig: "4WD",
    },
    part: {
      name: "Rear Axle Assembly with E-Locker Differential",
      partNumber: "41110-0KK20",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Severe offroad impact cracked casing. Complete sealed assembly required.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-09",
    status: "Sourcing",
    quotedValue: 3183.63,
    actionRequired: "Awaiting heavy cargo airfreight confirmation from carrier",
    actionType: "view_details",
    messages: [],
  },
  {
    id: "req-138",
    requestNumber: "AutoHub-P-138",
    vehicle: {
      make: "Toyota",
      model: "Land Cruiser Prado",
      year: 2020,
      vin: "GDJ150-004812",
      registration: "LCP401",
      engine: "1GD-FTV (2.8L)",
      variant: "VX Limited",
      transmission: "6-Speed Auto",
      driveConfig: "Full-time 4WD",
    },
    part: {
      name: "KDSS Hydraulic Cylinder Actuator Assembly (Front)",
      partNumber: "48805-60030",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "KDSS warning light active, valve seal failure.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-09",
    status: "Sourcing",
    quotedValue: 1495.0,
    messages: [],
  },
  {
    id: "req-135",
    requestNumber: "AutoHub-P-135",
    vehicle: {
      make: "Nissan",
      model: "Navara",
      year: 2021,
      vin: "MNTVCPD2300084",
      registration: "NAV321",
      engine: "YS23DDTi Twin Turbo",
      variant: "ST-X 4WD",
      transmission: "7-Speed Auto",
      driveConfig: "4WD",
    },
    part: {
      name: "Garrett Twin Turbocharger Assembly with Electronic Actuator",
      partNumber: "14411-5X01B",
      quantity: 1,
      preference: "OEM Supplier Tier 1",
      condition: "Brand New Certified Aftermarket",
    },
    supporting: {
      notes: "Garrett OEM spec unit acceptable.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-03",
    status: "Shipped",
    quotedValue: 1850.0,
    shipment: {
      trackingNumber: "MF-NZ-98234812",
      carrier: "Mainfreight Air & Ocean NZ",
      carrierWebsite: "https://www.mainfreight.com",
      currentMilestone: "Arrived in NZ",
      origin: "Tokyo Haneda Gateway (HND)",
      destination: "SP Motors Auckland (Penrose)",
      estimatedDelivery: "Tomorrow, 11 Sep 2026",
      dispatchedAt: "2026-09-06",
      milestonesHistory: [
        {
          milestone: "Received At Shipping Facility",
          location: "Autohub Tokyo Hub, Japan",
          timestamp: "06 Sep • 09:00 AM",
          description: "Consigned to export packaging & barcode scanned",
          isCompleted: true,
        },
        {
          milestone: "In Transit",
          location: "Flight NZ90 / NRT to AKL",
          timestamp: "07 Sep • 06:30 PM",
          description: "Departed Tokyo Narita International Airport",
          isCompleted: true,
        },
        {
          milestone: "Arrived in NZ",
          location: "Auckland International Cargo Terminal (AKL)",
          timestamp: "09 Sep • 07:15 AM",
          description: "Aircraft touched down, cargo transferred to bonded warehouse",
          isCompleted: true,
        },
        {
          milestone: "Out For Delivery",
          location: "Penrose Depot Dispatch Hub",
          timestamp: "Scheduled: Tomorrow morning",
          description: "Assigned to dedicated metro courier route",
          isCompleted: false,
        },
        {
          milestone: "Delivered",
          location: "SP Motors Workshop",
          timestamp: "Scheduled: Tomorrow by 2:00 PM",
          description: "Workshop reception signature required",
          isCompleted: false,
        },
      ],
    },
    messages: [],
  },
  {
    id: "req-120",
    requestNumber: "AutoHub-P-120",
    vehicle: {
      make: "Honda",
      model: "Civic Type R",
      year: 2022,
      vin: "FK8-2009141",
      registration: "CTR888",
      engine: "K20C1 Turbo VTEC",
      variant: "FK8 Track Edition",
      transmission: "6-Speed Manual",
      driveConfig: "FWD",
    },
    part: {
      name: "Front Brembo Monobloc 4-Piston Calipers (Pair, Red)",
      partNumber: "45018-TGH-A01",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Genuine Honda Type R Brembo red calipers.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-02",
    status: "Ordered",
    quotedValue: 1980.0,
    payment: {
      id: "pay-120",
      requestId: "req-120",
      invoiceNumber: "INV-2026-00810",
      amount: 1980.0,
      currency: "NZD",
      status: "Paid",
      paymentMethod: "Bank Transfer",
      paymentReference: "AutoHub-P-120",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
      },
      paidAt: "2026-09-10 09:20 NZST",
      dueDate: "2026-09-15",
    },
    messages: [
      {
        id: "msg-6",
        senderName: "Operations Dispatch",
        senderRole: "Autohub Operations",
        message: "Payment settled on SP Motors 30-Day Credit Account. Official PO dispatched to Honda Japan central parts warehouse.",
        timestamp: "Today • 09:20 AM",
      },
    ],
  },
  {
    id: "req-115",
    requestNumber: "AutoHub-P-115",
    vehicle: {
      make: "Subaru",
      model: "WRX STI",
      year: 2020,
      vin: "VAB-029410",
      registration: "STI555",
      engine: "EJ207 / EJ257",
      variant: "Final Edition",
      transmission: "6-Speed Manual",
      driveConfig: "AWD",
    },
    part: {
      name: "Subaru EJ207 Cylinder Heads (Pair, Complete with Valvetrain)",
      partNumber: "11039-AB910",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Factory assembled heads.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-08-28",
    status: "Shipped",
    quotedValue: 2420.0,
    shipment: {
      trackingNumber: "DHL-NZ-77192830",
      carrier: "DHL Express New Zealand",
      carrierWebsite: "https://www.dhl.com",
      currentMilestone: "Out For Delivery",
      origin: "Yokohama, Japan",
      destination: "SP Motors Auckland (Penrose)",
      estimatedDelivery: "Today, 10 Sep by 4:00 PM",
      dispatchedAt: "2026-09-01",
      milestonesHistory: [
        {
          milestone: "Received At Shipping Facility",
          location: "Yokohama Hub",
          timestamp: "01 Sep • 10:00 AM",
          description: "Packed in timber crate",
          isCompleted: true,
        },
        {
          milestone: "In Transit",
          location: "DHL Express Airway",
          timestamp: "03 Sep • 11:30 PM",
          description: "Air freight dispatch via Tokyo",
          isCompleted: true,
        },
        {
          milestone: "Arrived in NZ",
          location: "Auckland Airport Hub",
          timestamp: "08 Sep • 04:15 PM",
          description: "Unloaded at DHL Express Gateway",
          isCompleted: true,
        },
        {
          milestone: "Out For Delivery",
          location: "Penrose Metro Courier Van #14",
          timestamp: "Today • 08:15 AM",
          description: "Loaded onto courier van for delivery to SP Motors Penrose",
          isCompleted: false,
        },
      ],
    },
    messages: [],
  },
  {
    id: "req-110",
    requestNumber: "AutoHub-P-110",
    vehicle: {
      make: "Lexus",
      model: "RX450h",
      year: 2021,
      vin: "GYL25-001924",
      registration: "LEX450",
      engine: "2GR-FXS 3.5L V6 Hybrid",
      variant: "F Sport",
      transmission: "E-CVT",
      driveConfig: "E-Four AWD",
    },
    part: {
      name: "Hybrid Inverter & Power Management Converter Assembly",
      partNumber: "G9200-48190",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Sealed OEM inverter unit.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-08-20",
    status: "Completed",
    quotedValue: 3850.0,
    payment: {
      id: "pay-110",
      requestId: "req-110",
      invoiceNumber: "INV-2026-00620",
      amount: 3850.0,
      currency: "NZD",
      status: "Paid",
      paymentMethod: "Bank Transfer",
      paymentReference: "AutoHub-P-110",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
      },
      paidAt: "2026-08-24",
      dueDate: "2026-08-30",
    },
    messages: [],
  },
];

export const INITIAL_ACTIVITIES: ProcurementActivity[] = [
  {
    id: "act-1",
    timestamp: "2026-09-10T10:42:00Z",
    timeLabel: "Today • 10:42 AM",
    title: "Quote generated for AutoHub-P-128",
    description: "OEM Toyota Control Arm issued from Nagoya stock.",
    type: "quote",
    requestId: "req-128",
  },
  {
    id: "act-2",
    timestamp: "2026-09-10T09:20:00Z",
    timeLabel: "Today • 09:20 AM",
    title: "Payment received for AutoHub-P-120",
    description: "$1,980.00 settled. Purchase order dispatched to Honda supplier.",
    type: "payment",
    requestId: "req-120",
  },
  {
    id: "act-3",
    timestamp: "2026-09-09T16:15:00Z",
    timeLabel: "Yesterday • 04:15 PM",
    title: "Consignment arrived in NZ for AutoHub-P-115",
    description: "Aircraft landed at Auckland Airport. Scheduled for local courier handover.",
    type: "shipment",
    requestId: "req-115",
  },
  {
    id: "act-4",
    timestamp: "2026-09-09T14:00:00Z",
    timeLabel: "Yesterday • 02:00 PM",
    title: "Shipment in transit (Mainfreight Air)",
    description: "AutoHub-P-135 departed Narita (NRT) to Auckland International (AKL).",
    type: "shipment",
    requestId: "req-135",
  },
  {
    id: "act-5",
    timestamp: "2026-09-08T11:30:00Z",
    timeLabel: "08 Sep • 11:30 AM",
    title: "New Part Request Submitted: AutoHub-P-128",
    description: "Toyota Hiace 2019 Left Front Lower Control Arm logged for SP Motors Penrose.",
    type: "request",
    requestId: "req-128",
  },
];

export const INITIAL_NOTIFICATIONS: PortalNotification[] = [
  {
    id: "notif-1",
    type: "Quote Available",
    title: "Quote Available for AutoHub-P-128",
    description: "Toyota Hiace 2019 control arm is ready for customer review at $485.00 NZD.",
    timestamp: "15m ago",
    read: false,
    requestId: "req-128",
  },
  {
    id: "notif-2",
    type: "Payment Received",
    title: "Payment Received: AutoHub-P-120",
    description: "$1,980.00 confirmed via Bank Transfer. PO sent to Honda factory.",
    timestamp: "1h ago",
    read: false,
    requestId: "req-120",
  },
  {
    id: "notif-3",
    type: "Delivery Out",
    title: "Delivery Out: AutoHub-P-115",
    description: "Subaru WRX STI cylinder heads onboard courier van for SP Motors Penrose.",
    timestamp: "2h ago",
    read: false,
    requestId: "req-115",
  },
  {
    id: "notif-4",
    type: "Shipment Arrived",
    title: "Shipment Arrived in NZ: AutoHub-P-135",
    description: "Nissan Navara turbocharger landed at Auckland Cargo terminal.",
    timestamp: "1d ago",
    read: true,
    requestId: "req-135",
  },
  {
    id: "notif-5",
    type: "Registration Approval",
    title: "Trade Account Approved",
    description: "SP Motors Auckland trade account active with $50,000 credit limit.",
    timestamp: "2w ago",
    read: true,
  },
];
