import {
  PartRequest,
  CustomerRecord,
  StaffUser,
  Supplier,
  PortalNotification,
  SavedAddress,
} from "@/types/shared";

// ─── Shared Addresses ──────────────────────────────────────

export const SHARED_ADDRESSES: SavedAddress[] = [
  {
    id: "addr-01",
    label: "AutoCare Auckland - Penrose Workshop",
    recipientName: "Dave Miller (Workshop Manager)",
    businessName: "AutoCare Auckland",
    streetAddress: "142 Great South Road",
    suburb: "Penrose",
    city: "Auckland",
    postalCode: "1061",
    phone: "+64 9 525 1122",
    isDefault: true,
  },
  {
    id: "addr-02",
    label: "SP Motors Ltd - Central Workshop",
    recipientName: "James Wilson (Workshop Reception)",
    businessName: "SP Motors Ltd",
    streetAddress: "34 Great South Road",
    suburb: "Penrose",
    city: "Auckland",
    postalCode: "1061",
    phone: "+64 9 525 8890",
    isDefault: true,
  },
  {
    id: "addr-03",
    label: "Precision European Workshop",
    recipientName: "Liam Davies",
    businessName: "Precision European Ltd",
    streetAddress: "88 Cook Street",
    suburb: "CBD",
    city: "Auckland",
    postalCode: "1010",
    phone: "+64 9 377 8899",
    isDefault: true,
  },
];

// ─── Centralized Mock Customers ────────────────────────────

export const MOCK_CUSTOMERS: CustomerRecord[] = [
  {
    id: "cust-01",
    businessName: "AutoCare Auckland",
    contactName: "Dave Miller",
    email: "dave@autocare.co.nz",
    phone: "+64 9 525 1122",
    status: "Active",
    registrationDate: "2025-11-14",
    requestCount: 6,
    deliveryAddress: SHARED_ADDRESSES[0],
    notes: "Preferred trade partner for light commercial vans and JDM imports.",
  },
  {
    id: "cust-02",
    businessName: "SP Motors Ltd",
    contactName: "James Wilson",
    email: "james.wilson@spmotors.co.nz",
    phone: "+64 21 555 0192",
    status: "Active",
    registrationDate: "2025-08-20",
    requestCount: 14,
    deliveryAddress: SHARED_ADDRESSES[1],
    notes: "High-volume workshop. Requires expedited airfreight options.",
  },
  {
    id: "cust-03",
    businessName: "Precision European",
    contactName: "Liam Davies",
    email: "liam@precisioneuro.co.nz",
    phone: "+64 9 377 8899",
    status: "Active",
    registrationDate: "2026-01-10",
    requestCount: 4,
    deliveryAddress: SHARED_ADDRESSES[2],
    notes: "Specializes in German marques (BMW, Audi, Mercedes-Benz).",
  },
  {
    id: "cust-04",
    businessName: "Westside Fleet Services",
    contactName: "Brenda Scott",
    email: "brenda@westsidefleet.co.nz",
    phone: "+64 9 834 2211",
    status: "Pending Approval",
    registrationDate: "2026-09-10",
    requestCount: 1,
    notes: "New trade application received today. Awaiting business verification.",
  },
  {
    id: "cust-05",
    businessName: "South Island Commercials",
    contactName: "Tony Bell",
    email: "tony@sicommercials.co.nz",
    phone: "+64 3 366 4433",
    status: "Suspended",
    registrationDate: "2025-04-12",
    requestCount: 3,
    notes: "Account temporarily on hold pending updated company registration.",
  },
];

// ─── Centralized Mock Staff Users (RBAC) ───────────────────

export const MOCK_STAFF_USERS: StaffUser[] = [
  {
    id: "user-staff-04",
    name: "David Vance",
    email: "david.vance@JDMHUB.io",
    role: "Administrator",
    status: "Active",
    lastLogin: "Today, 10:30 AM",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    department: "Executive Management",
    title: "Operations & Procurement Director",
  },
  {
    id: "user-staff-01",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@JDMHUB.io",
    role: "Procurement",
    status: "Active",
    lastLogin: "Today, 10:14 AM",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    department: "Strategic Sourcing",
    title: "Senior Sourcing Specialist",
  },
  {
    id: "user-staff-02",
    name: "Marcus Thorne",
    email: "marcus.thorne@JDMHUB.io",
    role: "Operations",
    status: "Active",
    lastLogin: "Today, 09:45 AM",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    department: "Logistics & Fulfillment",
    title: "Operations & Logistics Lead",
  },
  {
    id: "user-staff-03",
    name: "Rachel Adams",
    email: "rachel.adams@JDMHUB.io",
    role: "Finance",
    status: "Active",
    lastLogin: "Today, 08:30 AM",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    department: "Finance & Accounts",
    title: "Finance & Accounts Specialist",
  },
  {
    id: "user-staff-05",
    name: "Akira Yamamoto",
    email: "akira.yamamoto@JDMHUB.io",
    role: "Operations",
    status: "Active",
    lastLogin: "Today, 11:15 AM",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    department: "Operations & Logistics",
    title: "Logistics Specialist (Japan)",
  },
];

// ─── Centralized Mock Suppliers ────────────────────────────

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "sup-01",
    name: "Toyota Tsusho Parts Japan",
    contact: "Kenji Yamamoto",
    email: "k.yamamoto@toyotatsusho-parts.jp",
    phone: "+81 52 584 5000",
    country: "Japan",
    category: "Genuine OEM Japanese",
    specializations: ["Toyota", "Lexus", "Daihatsu"],
    rating: 5,
    status: "Active",
  },
  {
    id: "sup-02",
    name: "Nagoya Auto Parts Co.",
    contact: "Haruki Tanaka",
    email: "h.tanaka@nagoya-autoparts.co.jp",
    phone: "+81 52 201 3300",
    country: "Japan",
    category: "Aftermarket & Tier 1 OEM",
    specializations: ["Toyota", "Honda", "Mazda", "Subaru"],
    rating: 4,
    status: "Active",
  },
  {
    id: "sup-03",
    name: "Pacific Motor Spares AU",
    contact: "Steve Mitchell",
    email: "steve@pacificmotorspares.com.au",
    phone: "+61 3 9876 5432",
    country: "Australia",
    category: "Commercial & Fleet Spares",
    specializations: ["Nissan", "Isuzu", "Mitsubishi", "Ford"],
    rating: 4,
    status: "Active",
  },
  {
    id: "sup-04",
    name: "Hiroshima OEM Direct",
    contact: "Yuki Sato",
    email: "y.sato@hiroshima-oem.jp",
    phone: "+81 82 241 8800",
    country: "Japan",
    category: "Mazda & JDM Specialist",
    specializations: ["Mazda", "Rotary Parts", "Genuine Lighting"],
    rating: 5,
    status: "Active",
  },
  {
    id: "sup-05",
    name: "Bangkok Auto Components",
    contact: "Somchai Prasert",
    email: "somchai@bkkauto.co.th",
    phone: "+66 2 714 2200",
    country: "Thailand",
    category: "Aftermarket Suspension & Brakes",
    specializations: ["Toyota Hilux", "Isuzu D-Max", "Ford Ranger"],
    rating: 3,
    status: "Active",
  },
];

// ─── Centralized Mock Requests ─────────────────────────────
// Contains benchmark AutoHub-P-000123 as specified in prompt

export const INITIAL_SHARED_REQUESTS: PartRequest[] = [
  // ── 1. Benchmark Request: AutoHub-P-000123 (Awaiting Payment, Unpaid) ──
  {
    id: "req-000123",
    requestNumber: "AutoHub-P-000123",
    customerId: "cust-01",
    customerName: "AutoCare Auckland",
    contactName: "Dave Miller",
    customerEmail: "dave@autocare.co.nz",
    customerPhone: "+64 9 525 1122",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "GDH201-0012845",
      registration: "MTB842",
      engine: "1GD-FTV (2.8L Turbo Diesel)",
      variant: "DX / Long Wheelbase",
      transmission: "6-Speed Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm",
      partNumber: "48069-26150",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Commercial fleet vehicle currently on hoist bay 1. Bushing ruptured, need urgent replacement to return van to service.",
      photos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80",
      ],
      documents: ["Hiace_2019_Fitment_Check.pdf"],
    },
    deliveryAddress: SHARED_ADDRESSES[0],
    dateSubmitted: "2026-09-11",
    lastUpdated: "Today",
    status: "Awaiting Payment",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 410.0,
    customerResponse: "Accepted",
    supplierQuotations: [
      {
        id: "sq-123-1",
        supplierId: "sup-02",
        supplierName: "Nagoya Auto Parts Co.",
        supplierContact: "Haruki Tanaka",
        supplierCountry: "Japan",
        supplierPartRef: "NAP-48069-TY",
        availability: "In Stock",
        supplierCost: 245.0,
        supplierFreight: 30.0,
        leadTimeDays: 5,
        condition: "Genuine",
        notes: "Factory packaged Toyota OEM part. Available for dispatch tomorrow.",
        isSelected: true,
        createdAt: "Today, 09:30 AM",
      },
      {
        id: "sq-123-2",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "TT-4806926150",
        availability: "In Stock",
        supplierCost: 260.0,
        supplierFreight: 35.0,
        leadTimeDays: 4,
        condition: "Genuine",
        notes: "Direct Toyota distribution center stock.",
        isSelected: false,
        createdAt: "Today, 09:45 AM",
      },
      {
        id: "sq-123-3",
        supplierId: "sup-03",
        supplierName: "Pacific Motor Spares AU",
        supplierContact: "Steve Mitchell",
        supplierCountry: "Australia",
        supplierPartRef: "PMS-CA-8921",
        availability: "Available",
        supplierCost: 220.0,
        supplierFreight: 45.0,
        leadTimeDays: 7,
        condition: "Aftermarket",
        notes: "Premium aftermarket replacement with polyurethane bushings.",
        isSelected: false,
        createdAt: "Today, 10:00 AM",
      },
    ],
    selectedQuotationId: "sq-123-1",
    costCalculation: {
      supplierCost: 245.0,
      supplierFreight: 30.0,
      autohubMarginPercent: 20,
      autohubMarginAmount: 50.0,
      customerSellPrice: 325.0,
      customerFreight: 85.0, // ONE manual flat freight value
      totalCustomerQuote: 410.0,
    },
    customerQuoteVersions: [
      {
        version: 1,
        date: "2026-09-11",
        sellPrice: 325.0,
        freight: 85.0,
        totalAmount: 410.0,
        estimatedTransitDays: 5,
        notes: "Genuine OEM Toyota Left Front Lower Control Arm with integrated bush and pre-greased ball joint. Factory Nagoya batch QA verified.",
        terms: "Standard Autohub B2B Trade Terms. 12-month replacement warranty.",
        sentAt: "Today, 10:15 AM",
        status: "Accepted",
        createdBy: "Sarah Jenkins",
        quotePhotos: [
          "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
        ],
      },
    ],
    customerQuote: {
      id: "quote-123",
      requestId: "req-000123",
      version: 1,
      itemDescription: "Genuine OEM Toyota Front Lower Suspension Arm (LH) assembly with factory bushings.",
      oemNumber: "48069-26150",
      quantity: 1,
      unitPrice: 325.0,
      subtotal: 325.0,
      airFreightCost: 125,
      seaFreightCost: 85,
      freightNote: "Standard consolidated airfreight to Auckland workshop",
      gstAmount: 53.48,
      totalAmount: 410.0,
      currency: "NZD",
      estimatedTransitDays: 5,
      validUntil: "2026-09-18",
      termsAccepted: true,
      procurementTerms: "Backed by Autohub Trade Warranty. Returns accepted within 14 days for uninstalled parts.",
      notes: "Direct Nagoya warehouse allocation reserved for 48 hours. Inspected and approved by Autohub Japan team.",
      supplierLocation: "Autohub Nagoya Hub, Japan",
      quotePhotos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
      ],
    },
    quotation: {
      id: "quote-123",
      requestId: "req-000123",
      version: 1,
      itemDescription: "Genuine OEM Toyota Front Lower Suspension Arm (LH) assembly with factory bushings.",
      oemNumber: "48069-26150",
      quantity: 1,
      unitPrice: 325.0,
      subtotal: 325.0,
      airFreightCost: 125,
      seaFreightCost: 85,
      freightNote: "Standard consolidated airfreight to Auckland workshop",
      gstAmount: 53.48,
      totalAmount: 410.0,
      currency: "NZD",
      estimatedTransitDays: 5,
      validUntil: "2026-09-18",
      termsAccepted: true,
      procurementTerms: "Backed by Autohub Trade Warranty. Returns accepted within 14 days for uninstalled parts.",
      notes: "Direct Nagoya warehouse allocation reserved for 48 hours. Inspected and approved by Autohub Japan team.",
      supplierLocation: "Autohub Nagoya Hub, Japan",
      quotePhotos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
      ],
    },
    quoteAcceptance: {
      acceptedAt: "Today, 10:45 AM",
      acceptedBy: "Dave Miller",
      userRole: "Workshop Manager",
      termsAccepted: true,
      vehicleVerified: true,
      partVerified: true,
      addressVerified: true,
      freightCost: 85,
      selectedFreightType: "Sea",
    },
    payment: {
      id: "pay-123",
      requestId: "req-000123",
      invoiceNumber: "INV-2026-00123",
      amount: 410.0,
      currency: "NZD",
      status: "Unpaid", // Payment is Unpaid -> Supplier order LOCKED!
      paymentReference: "AutoHub-P-000123",
      dueDate: "2026-09-16",
      lastUpdated: "Today",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
        swiftBic: "ANZBNZ22",
      },
    },
    documents: [
      {
        id: "doc-123-1",
        name: "Hiace_2019_Fitment_Check.pdf",
        type: "Customer",
        size: "1.4 MB",
        uploadedAt: "Today, 09:12 AM",
        uploadedBy: "Dave Miller",
      },
      {
        id: "doc-123-2",
        name: "Nagoya_Supplier_Quote_NAP-48069.pdf",
        type: "Supplier",
        size: "820 KB",
        uploadedAt: "Today, 09:32 AM",
        uploadedBy: "Sarah Jenkins",
      },
    ],
    internalNotes: [
      {
        id: "in-123-1",
        author: "Sarah Jenkins",
        role: "Procurement",
        text: "Supplier Nagoya Auto Parts has 3 units in stock. Price confirmed at NZ$245 + NZ$30 freight. Quote sent to customer at NZ$410 incl NZ$85 flat freight.",
        timestamp: "Today, 10:18 AM",
      },
      {
        id: "in-123-2",
        author: "Dave Miller",
        role: "Customer",
        text: "Customer accepted quote. Waiting for accounts to clear payment before order release.",
        timestamp: "Today, 10:46 AM",
        isCustomerVisible: true,
      },
    ],
    activity: [
      {
        id: "act-123-1",
        timestamp: "Today, 09:12 AM",
        timeLabel: "09:12 AM",
        title: "Request submitted",
        description: "Request AutoHub-P-000123 submitted by Dave Miller (AutoCare Auckland).",
        actor: "Dave Miller",
        type: "status",
      },
      {
        id: "act-123-2",
        timestamp: "Today, 09:20 AM",
        timeLabel: "09:20 AM",
        title: "Request assigned",
        description: "Assigned to Sarah Jenkins (Procurement Desk).",
        actor: "David Vance",
        type: "status",
      },
      {
        id: "act-123-3",
        timestamp: "Today, 09:30 AM",
        timeLabel: "09:30 AM",
        title: "Supplier quote added",
        description: "Quotation received from Nagoya Auto Parts Co. for NZ$245.00.",
        actor: "Sarah Jenkins",
        type: "quote",
      },
      {
        id: "act-123-4",
        timestamp: "Today, 10:15 AM",
        timeLabel: "10:15 AM",
        title: "Customer quote created",
        description: "Quote v1 created for NZ$410.00 (Part: $325, Freight: $85) and dispatched to customer.",
        actor: "Sarah Jenkins",
        type: "quote",
      },
      {
        id: "act-123-5",
        timestamp: "Today, 10:45 AM",
        timeLabel: "10:45 AM",
        title: "Customer accepted quote",
        description: "Quote accepted by Dave Miller. Status moved to Awaiting Payment.",
        actor: "Dave Miller",
        type: "quote",
      },
    ],
    actionRequired: "Settle invoice via Bank Transfer or Card",
    actionType: "pay_now",
  },

  // ── 2. Request: AutoHub-P-000145 (Status: Submitted / New) ──
  {
    id: "req-000145",
    requestNumber: "AutoHub-P-000145",
    customerId: "cust-01",
    customerName: "AutoCare Auckland",
    contactName: "Dave Miller",
    customerEmail: "dave@autocare.co.nz",
    customerPhone: "+64 9 525 1122",
    vehicle: {
      make: "Toyota",
      model: "RAV4",
      year: 2022,
      vin: "MXAA54-0018923",
      registration: "RAV422",
      engine: "M20A-FKS (2.0L Dynamic Force)",
      variant: "GX AWD",
      transmission: "CVT",
      driveConfig: "AWD",
    },
    part: {
      name: "Front Brake Disc Rotor Set (Pair)",
      partNumber: "43512-0R080",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Customer reports disc vibration under high-speed braking. Requires genuine rotors for warranty compliance.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[0],
    dateSubmitted: "2026-09-11",
    lastUpdated: "Today",
    status: "Submitted",
    supplierQuotations: [],
    customerQuoteVersions: [],
    documents: [],
    internalNotes: [],
    activity: [
      {
        id: "act-145-1",
        timestamp: "Today, 10:10 AM",
        timeLabel: "10:10 AM",
        title: "Request submitted",
        description: "New parts request received from AutoCare Auckland.",
        actor: "Dave Miller",
        type: "status",
      },
    ],
    actionRequired: "Waiting for Autohub specialist sourcing review",
    actionType: "none",
  },

  // ── 3. Request: AutoHub-P-000138 (Status: Sourcing) ──
  {
    id: "req-000138",
    requestNumber: "AutoHub-P-000138",
    customerId: "cust-03",
    customerName: "Precision European",
    contactName: "Liam Davies",
    customerEmail: "liam@precisioneuro.co.nz",
    customerPhone: "+64 9 377 8899",
    vehicle: {
      make: "Audi",
      model: "A4",
      year: 2020,
      vin: "WAUZZZF45LA091244",
      registration: "NLE482",
      engine: "2.0 TFSI (EA888 Gen 3)",
      variant: "40 TFSI S-line",
      transmission: "7-Speed S-Tronic",
      driveConfig: "FWD",
    },
    part: {
      name: "Engine Water Pump Assembly with Thermostat Housing",
      partNumber: "06L121111H",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Coolant leak from plastic thermostat housing seam. Critical fitment check needed.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[2],
    dateSubmitted: "2026-09-10",
    lastUpdated: "Yesterday",
    status: "Sourcing",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    supplierQuotations: [
      {
        id: "sq-138-1",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "VAG-06L121111H",
        availability: "In Stock",
        supplierCost: 380.0,
        supplierFreight: 45.0,
        leadTimeDays: 6,
        condition: "Genuine",
        notes: "OE Pierburg unit in VAG factory packaging.",
        isSelected: true,
        createdAt: "Yesterday, 03:20 PM",
      },
      {
        id: "sq-138-2",
        supplierId: "sup-03",
        supplierName: "Pacific Motor Spares AU",
        supplierContact: "Steve Mitchell",
        supplierCountry: "Australia",
        supplierPartRef: "INA-538036010",
        availability: "Available",
        supplierCost: 340.0,
        supplierFreight: 55.0,
        leadTimeDays: 8,
        condition: "Aftermarket",
        notes: "INA OEM equivalent thermal management module.",
        isSelected: false,
        createdAt: "Yesterday, 04:00 PM",
      },
    ],
    selectedQuotationId: "sq-138-1",
    customerQuoteVersions: [],
    documents: [],
    internalNotes: [
      {
        id: "in-138-1",
        author: "Sarah Jenkins",
        role: "Procurement",
        text: "Supplier quotes collected. Ready to finalize customer quote calculation.",
        timestamp: "Yesterday, 04:30 PM",
      },
    ],
    activity: [
      {
        id: "act-138-1",
        timestamp: "2026-09-10T11:00:00Z",
        timeLabel: "11:00 AM",
        title: "Request submitted",
        description: "Request submitted by Liam Davies.",
        actor: "Liam Davies",
        type: "status",
      },
      {
        id: "act-138-2",
        timestamp: "2026-09-10T14:30:00Z",
        timeLabel: "02:30 PM",
        title: "Moved to Sourcing",
        description: "Active supplier RFQ sent to Japanese and Australian suppliers.",
        actor: "Sarah Jenkins",
        type: "status",
      },
    ],
    actionRequired: "Sourcing in progress with international suppliers",
    actionType: "none",
  },

  // ── 4. Request: AutoHub-P-000128 (Status: Quoted / Review) ──
  {
    id: "req-000128",
    requestNumber: "AutoHub-P-000128",
    customerId: "cust-02",
    customerName: "SP Motors Ltd",
    contactName: "James Wilson",
    customerEmail: "james.wilson@spmotors.co.nz",
    customerPhone: "+64 21 555 0192",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "GDH201-0012845",
      registration: "MTB842",
      engine: "1GD-FTV (2.8L Turbo Diesel)",
      variant: "DX / Long Wheelbase",
      transmission: "6-Speed Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm",
      partNumber: "48069-26150",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Workshop hoist bay 2. Bushing torn. Urgent dispatch requested.",
      photos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80",
      ],
      documents: ["Fitment_Verification_Hiace_2019.pdf"],
    },
    deliveryAddress: SHARED_ADDRESSES[1],
    dateSubmitted: "2026-09-08",
    lastUpdated: "2 days ago",
    status: "Quoted",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 485.0,
    customerQuoteVersions: [
      {
        version: 1,
        date: "2026-09-09",
        sellPrice: 420.0,
        freight: 65.0,
        totalAmount: 485.0,
        estimatedTransitDays: 5,
        notes: "Verified genuine OEM Toyota Part (Nagoya Sourcing Hub). Holographic seal and factory inspection certificate verified. Pre-lubricated ball joint and rubber bush condition 100% brand new. Allocated for dispatch upon quote confirmation.",
        terms: "Autohub 12-Month Trade Warranty.",
        sentAt: "2026-09-09T14:00:00Z",
        status: "Sent",
        createdBy: "Sarah Jenkins",
        quotePhotos: [
          "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
          "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
        ],
      },
    ],
    customerQuote: {
      id: "quote-128",
      requestId: "req-000128",
      version: 1,
      itemDescription: "OEM Toyota Front Lower Suspension Arm (LH) with integrated high-durability bush.",
      oemNumber: "48069-26150",
      quantity: 1,
      unitPrice: 420.0,
      subtotal: 420.0,
      airFreightCost: 105,
      seaFreightCost: 65,
      freightNote: "Consolidated express air freight to Auckland",
      gstAmount: 63.26,
      totalAmount: 485.0,
      currency: "NZD",
      estimatedTransitDays: 5,
      validUntil: "2026-09-15",
      termsAccepted: false,
      procurementTerms: "Backed by 12-month Autohub Trade Warranty.",
      notes: "Verified genuine OEM Toyota Part (Nagoya Sourcing Hub). Holographic seal and factory inspection certificate verified. Pre-lubricated ball joint and rubber bush condition 100% brand new. Allocated for dispatch upon quote confirmation.",
      supplierLocation: "Autohub Nagoya Hub, Japan",
      quotePhotos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
      ],
    },
    quotation: {
      id: "quote-128",
      requestId: "req-000128",
      version: 1,
      itemDescription: "OEM Toyota Front Lower Suspension Arm (LH) with integrated high-durability bush.",
      oemNumber: "48069-26150",
      quantity: 1,
      unitPrice: 420.0,
      subtotal: 420.0,
      airFreightCost: 105,
      seaFreightCost: 65,
      freightNote: "Consolidated express air freight to Auckland",
      gstAmount: 63.26,
      totalAmount: 485.0,
      currency: "NZD",
      estimatedTransitDays: 5,
      validUntil: "2026-09-15",
      termsAccepted: false,
      procurementTerms: "Backed by 12-month Autohub Trade Warranty.",
      notes: "Verified genuine OEM Toyota Part (Nagoya Sourcing Hub). Holographic seal and factory inspection certificate verified. Pre-lubricated ball joint and rubber bush condition 100% brand new. Allocated for dispatch upon quote confirmation.",
      supplierLocation: "Autohub Nagoya Hub, Japan",
      quotePhotos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
      ],
    },
    supplierQuotations: [
      {
        id: "sq-128-1",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "TT-48069-26150",
        availability: "In Stock",
        supplierCost: 310.0,
        supplierFreight: 35.0,
        leadTimeDays: 5,
        condition: "Genuine",
        notes: "Ready for export dispatch.",
        isSelected: true,
        createdAt: "2026-09-09T11:30:00Z",
      },
    ],
    selectedQuotationId: "sq-128-1",
    costCalculation: {
      supplierCost: 310.0,
      supplierFreight: 35.0,
      autohubMarginPercent: 22,
      autohubMarginAmount: 75.0,
      customerSellPrice: 420.0,
      customerFreight: 65.0,
      totalCustomerQuote: 485.0,
    },
    documents: [],
    internalNotes: [],
    activity: [
      {
        id: "act-128-1",
        timestamp: "2026-09-08T10:00:00Z",
        timeLabel: "10:00 AM",
        title: "Request submitted",
        description: "Submitted by James Wilson.",
        actor: "James Wilson",
        type: "status",
      },
      {
        id: "act-128-2",
        timestamp: "2026-09-09T14:00:00Z",
        timeLabel: "02:00 PM",
        title: "Customer quote created",
        description: "Quote v1 sent for NZ$485.00.",
        actor: "Sarah Jenkins",
        type: "quote",
      },
    ],
    actionRequired: "Review & approve quote to proceed to fulfillment",
    actionType: "review_quote",
  },

  // ── 5. Request: AutoHub-P-000137 (Status: Approved / Pending Payment) ──
  {
    id: "req-000137",
    requestNumber: "AutoHub-P-000137",
    customerId: "cust-01",
    customerName: "AutoCare Auckland",
    contactName: "Dave Miller",
    customerEmail: "dave@autocare.co.nz",
    customerPhone: "+64 9 525 1122",
    vehicle: {
      make: "Mazda",
      model: "CX-5",
      year: 2021,
      vin: "KF2P-302198",
      registration: "MZD521",
      engine: "SH-VPTS (2.2L SkyActiv-D)",
      variant: "Limited 4WD",
      transmission: "6-Speed Automatic",
      driveConfig: "AWD",
    },
    part: {
      name: "High Output Alternator Assembly (150A)",
      partNumber: "SH01-18-300B",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Battery charging warning triggered, diode pack failure confirmed.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[0],
    dateSubmitted: "2026-09-07",
    lastUpdated: "Yesterday",
    status: "Invoicing",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 720.0,
    customerResponse: "Accepted",
    customerQuote: {
      id: "quote-137",
      requestId: "req-000137",
      version: 1,
      itemDescription: "Genuine Mazda SkyActiv-D Alternator Assembly (150A) with decoupler pulley.",
      oemNumber: "SH01-18-300B",
      quantity: 1,
      unitPrice: 625.0,
      subtotal: 625.0,
      airFreightCost: 135, seaFreightCost: 95,
      gstAmount: 93.91,
      totalAmount: 720.0,
      currency: "NZD",
      estimatedTransitDays: 6,
      validUntil: "2026-09-14",
      termsAccepted: true,
      notes: "Genuine Mazda OEM alternator with verified decoupler pulley. Direct from Hiroshima OEM inventory. Bench tested 150A output confirmed.",
      supplierLocation: "Hiroshima Hub, Japan",
      quotePhotos: [
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
      ],
    },
    quotation: {
      id: "quote-137",
      requestId: "req-000137",
      version: 1,
      itemDescription: "Genuine Mazda SkyActiv-D Alternator Assembly (150A) with decoupler pulley.",
      oemNumber: "SH01-18-300B",
      quantity: 1,
      unitPrice: 625.0,
      subtotal: 625.0,
      airFreightCost: 135,
      seaFreightCost: 95,
      gstAmount: 93.91,
      totalAmount: 720.0,
      currency: "NZD",
      estimatedTransitDays: 6,
      validUntil: "2026-09-14",
      termsAccepted: true,
      notes: "Genuine Mazda OEM alternator with verified decoupler pulley. Direct from Hiroshima OEM inventory. Bench tested 150A output confirmed.",
      supplierLocation: "Hiroshima Hub, Japan",
      quotePhotos: [
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80",
      ],
    },
    customerQuoteVersions: [],
    supplierQuotations: [
      {
        id: "sq-137-1",
        supplierId: "sup-04",
        supplierName: "Hiroshima OEM Direct",
        supplierContact: "Yuki Sato",
        supplierCountry: "Japan",
        supplierPartRef: "HOD-SH0118300B",
        availability: "In Stock",
        supplierCost: 480.0,
        supplierFreight: 45.0,
        leadTimeDays: 6,
        condition: "Genuine",
        notes: "Direct from Hiroshima parts warehouse.",
        isSelected: true,
        createdAt: "2026-09-08T09:00:00Z",
      },
    ],
    selectedQuotationId: "sq-137-1",
    payment: {
      id: "pay-137",
      requestId: "req-000137",
      invoiceNumber: "INV-2026-00137",
      amount: 720.0,
      currency: "NZD",
      status: "Unpaid",
      paymentReference: "AutoHub-P-000137",
      dueDate: "2026-09-15",
    },
    documents: [],
    internalNotes: [],
    activity: [
      {
        id: "act-137-1",
        timestamp: "Yesterday, 02:00 PM",
        timeLabel: "02:00 PM",
        title: "Quote accepted by customer",
        description: "Customer accepted quote. Status is Invoicing. Awaiting tax invoice issuance.",
        actor: "Dave Miller",
        type: "quote",
      },
    ],
    actionRequired: "Raise and attach invoice PDF",
    actionType: "upload_invoice",
  },

  // ── 6. Request: AutoHub-P-000125 (Status: Ordered / Paid / Order Placed) ──
  {
    id: "req-000125",
    requestNumber: "AutoHub-P-000125",
    customerId: "cust-02",
    customerName: "SP Motors Ltd",
    contactName: "James Wilson",
    customerEmail: "james.wilson@spmotors.co.nz",
    customerPhone: "+64 21 555 0192",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "TRH200-0089122",
      registration: "NLE591",
      engine: "1TR-FE (2.0L Petrol)",
      variant: "GL High Roof",
      transmission: "Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm Assembly with Bushing & Ball Joint",
      partNumber: "48069-26140",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Commercial delivery van. Urgent dispatch requested.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[1],
    dateSubmitted: "2026-09-06",
    lastUpdated: "3 days ago",
    status: "Ordered",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 640.0,
    customerResponse: "Accepted",
    customerQuote: {
      id: "quote-125",
      requestId: "req-000125",
      version: 1,
      itemDescription: "OEM Toyota Front Lower Suspension Arm (LH) Assembly.",
      oemNumber: "48069-26140",
      quantity: 1,
      unitPrice: 560.0,
      subtotal: 560.0,
      airFreightCost: 120, seaFreightCost: 80,
      gstAmount: 83.48,
      totalAmount: 640.0,
      currency: "NZD",
      estimatedTransitDays: 5,
      validUntil: "2026-09-12",
      termsAccepted: true,
    },
    customerQuoteVersions: [],
    supplierQuotations: [
      {
        id: "sq-125-1",
        supplierId: "sup-02",
        supplierName: "Nagoya Auto Parts Co.",
        supplierContact: "Haruki Tanaka",
        supplierCountry: "Japan",
        supplierPartRef: "NAP-4806926140",
        availability: "In Stock",
        supplierCost: 410.0,
        supplierFreight: 40.0,
        leadTimeDays: 4,
        condition: "Genuine",
        notes: "Part packed and labeled for Autohub consolidation.",
        isSelected: true,
        createdAt: "2026-09-06T14:00:00Z",
      },
    ],
    selectedQuotationId: "sq-125-1",
    payment: {
      id: "pay-125",
      requestId: "req-000125",
      invoiceNumber: "INV-2026-00125",
      amount: 640.0,
      currency: "NZD",
      status: "Paid", // Payment is Paid -> Supplier Order placed!
      paymentReference: "AutoHub-P-000125-PAID",
      paidAt: "2026-09-07T11:00:00Z",
      dueDate: "2026-09-14",
    },
    supplierOrder: {
      id: "ord-125",
      supplierId: "sup-02",
      supplierName: "Nagoya Auto Parts Co.",
      supplierRef: "PO-AH-2026-0089",
      orderDate: "2026-09-07",
      cost: 410.0,
      freight: 40.0,
      total: 450.0,
      notes: "Direct order confirmed. Nagoya dispatch scheduled today.",
      documents: ["PO_0089_Nagoya.pdf"],
    },
    documents: [],
    internalNotes: [
      {
        id: "in-125-1",
        author: "Rachel Adams",
        role: "Finance",
        text: "Payment received in full (NZ$640.00). Unlocked for supplier purchasing.",
        timestamp: "2026-09-07T11:05:00Z",
      },
    ],
    activity: [
      {
        id: "act-125-1",
        timestamp: "2026-09-07T11:00:00Z",
        timeLabel: "11:00 AM",
        title: "Payment marked Paid",
        description: "Payment confirmed by Rachel Adams. Supplier Order unlocked.",
        actor: "Rachel Adams",
        type: "payment",
      },
      {
        id: "act-125-2",
        timestamp: "2026-09-07T11:30:00Z",
        timeLabel: "11:30 AM",
        title: "Supplier order placed",
        description: "PO-AH-2026-0089 placed with Nagoya Auto Parts Co.",
        actor: "Sarah Jenkins",
        type: "order",
      },
    ],
    actionRequired: "Supplier order placed. Awaiting dispatch & tracking number.",
    actionType: "none",
  },

  // ── 7. Request: AutoHub-P-000120 (Status: Shipped / In Transit milestone) ──
  {
    id: "req-000120",
    requestNumber: "AutoHub-P-000120",
    customerId: "cust-02",
    customerName: "SP Motors Ltd",
    contactName: "James Wilson",
    customerEmail: "james.wilson@spmotors.co.nz",
    customerPhone: "+64 21 555 0192",
    vehicle: {
      make: "Nissan",
      model: "Navara",
      year: 2020,
      vin: "MNTVC2D23A0041289",
      registration: "NAV420",
      engine: "YS23DDTT (2.3L Twin Turbo Diesel)",
      variant: "ST-X Double Cab",
      transmission: "7-Speed Automatic",
      driveConfig: "4WD",
    },
    part: {
      name: "Garrett Twin Turbocharger Assembly with Electronic Actuator",
      partNumber: "14411-4KH1A",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Severe oil blow-by and shaft play. Vehicle awaiting installation in South Island.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[1],
    dateSubmitted: "2026-09-01",
    lastUpdated: "Yesterday",
    status: "Shipped", // Top-level status: SHIPPED
    assignedStaff: "Marcus Thorne",
    assignedStaffRole: "Operations",
    quotedValue: 2450.0,
    customerResponse: "Accepted",
    customerQuote: {
      id: "quote-120",
      requestId: "req-000120",
      version: 1,
      itemDescription: "OEM Genuine Nissan Navara Garrett Twin Turbo Unit.",
      oemNumber: "14411-4KH1A",
      quantity: 1,
      unitPrice: 2270.0,
      subtotal: 2270.0,
      airFreightCost: 220, seaFreightCost: 180, // Manual freight
      gstAmount: 319.57,
      totalAmount: 2450.0,
      currency: "NZD",
      estimatedTransitDays: 7,
      validUntil: "2026-09-07",
      termsAccepted: true,
    },
    customerQuoteVersions: [],
    supplierQuotations: [],
    payment: {
      id: "pay-120",
      requestId: "req-000120",
      invoiceNumber: "INV-2026-00120",
      amount: 2450.0,
      currency: "NZD",
      status: "Paid",
      paymentReference: "AutoHub-P-000120-PAID",
      dueDate: "2026-09-08",
    },
    supplierOrder: {
      id: "ord-120",
      supplierId: "sup-01",
      supplierName: "Toyota Tsusho Parts Japan",
      supplierRef: "PO-AH-2026-0072",
      orderDate: "2026-09-03",
      cost: 1780.0,
      freight: 120.0,
      total: 1900.0,
      notes: "Shipped via DHL Express Nagoya.",
      documents: [],
    },
    shipment: {
      id: "ship-120",
      trackingNumber: "NZ982341772",
      carrier: "DHL Global Forwarding",
      carrierWebsite: "https://www.dhl.com",
      currentMilestone: "In Transit", // Current internal milestone inside SHIPPED
      origin: "Nagoya Consolidation Hub, Japan",
      destination: "SP Motors Ltd, Penrose, Auckland",
      estimatedDelivery: "2026-09-14",
      dispatchedAt: "2026-09-08T09:00:00Z",
      lastUpdated: "Yesterday, 04:15 PM",
      milestonesHistory: [
        {
          milestone: "Received At Shipping Facility",
          location: "Nagoya Hub, Japan",
          timestamp: "2026-09-08T09:00:00Z",
          description: "Consolidated, crate packed, and barcoded for international export.",
          isCompleted: true,
        },
        {
          milestone: "In Transit",
          location: "En Route to Auckland Airport (Flight JL0711)",
          timestamp: "2026-09-09T18:30:00Z",
          description: "Departed international export hub. On schedule.",
          isCompleted: true,
        },
        {
          milestone: "Arrived in NZ",
          location: "Auckland Cargo Terminal (AKL)",
          timestamp: "Scheduled for 2026-09-12",
          description: "Awaiting aircraft arrival and freight discharge.",
          isCompleted: false,
        },

        {
          milestone: "Out For Delivery",
          location: "Auckland Metro Courier Hub",
          timestamp: "Scheduled for 2026-09-14",
          description: "Final mile courier dispatch to Penrose workshop.",
          isCompleted: false,
        },
        {
          milestone: "Delivered",
          location: "SP Motors Ltd",
          timestamp: "Pending final delivery",
          description: "Recipient signature required.",
          isCompleted: false,
        },
      ],
    },
    documents: [],
    internalNotes: [
      {
        id: "in-120-1",
        author: "Marcus Thorne",
        role: "Operations",
        text: "Flight JL0711 departed Nagoya. Expect NZ arrival Saturday morning. Customs pre-clearance documents ready.",
        timestamp: "Yesterday, 04:20 PM",
      },
    ],
    activity: [
      {
        id: "act-120-1",
        timestamp: "2026-09-08T09:00:00Z",
        timeLabel: "09:00 AM",
        title: "Shipment created",
        description: "Dispatched from Nagoya Hub via DHL Global Forwarding (Tracking #NZ982341772).",
        actor: "Marcus Thorne",
        type: "shipment",
      },
      {
        id: "act-120-2",
        timestamp: "2026-09-09T18:30:00Z",
        timeLabel: "06:30 PM",
        title: "Shipment in transit",
        description: "Flight JL0711 en route to Auckland. Milestone updated: In Transit.",
        actor: "Marcus Thorne",
        type: "shipment",
      },
    ],
    actionRequired: "Shipment en route to Auckland. Tracking: NZ982341772",
    actionType: "view_details",
  },

  // ── 8. Request: AutoHub-P-000115 (Status: Delivered) ──
  {
    id: "req-000115",
    requestNumber: "AutoHub-P-000115",
    customerId: "cust-03",
    customerName: "Precision European",
    contactName: "Liam Davies",
    customerEmail: "liam@precisioneuro.co.nz",
    customerPhone: "+64 9 377 8899",
    vehicle: {
      make: "BMW",
      model: "320i",
      year: 2021,
      vin: "WBA5R12030FP89211",
      registration: "BMR321",
      engine: "B48B20 (2.0L Turbo)",
      variant: "M Sport G20",
      transmission: "8-Speed Steptronic",
      driveConfig: "RWD",
    },
    part: {
      name: "Electronic Power Steering Rack & Pinion Assembly",
      partNumber: "32106889214",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Internal torque sensor fault. Replaced under mechanical breakdown warranty.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[2],
    dateSubmitted: "2026-08-25",
    lastUpdated: "3 days ago",
    status: "Delivered",
    assignedStaff: "Marcus Thorne",
    assignedStaffRole: "Operations",
    quotedValue: 3890.0,
    customerResponse: "Accepted",
    customerQuote: {
      id: "quote-115",
      requestId: "req-000115",
      version: 1,
      itemDescription: "Brand New Genuine BMW G20 Variable Sport Steering Rack.",
      oemNumber: "32106889214",
      quantity: 1,
      unitPrice: 3640.0,
      subtotal: 3640.0,
      airFreightCost: 290, seaFreightCost: 250,
      gstAmount: 507.39,
      totalAmount: 3890.0,
      currency: "NZD",
      estimatedTransitDays: 6,
      validUntil: "2026-08-31",
      termsAccepted: true,
    },
    customerQuoteVersions: [],
    supplierQuotations: [],
    payment: {
      id: "pay-115",
      requestId: "req-000115",
      invoiceNumber: "INV-2026-00115",
      amount: 3890.0,
      currency: "NZD",
      status: "Paid",
      paymentReference: "AutoHub-P-000115-PAID",
      dueDate: "2026-09-01",
    },
    shipment: {
      id: "ship-115",
      trackingNumber: "MF-NZ-881920",
      carrier: "Mainfreight Air & Ocean",
      carrierWebsite: "https://www.mainfreight.com",
      currentMilestone: "Delivered",
      origin: "Munich, Germany",
      destination: "Precision European, CBD, Auckland",
      estimatedDelivery: "2026-09-08",
      dispatchedAt: "2026-08-29T10:00:00Z",
      deliveredAt: "2026-09-08T14:22:00Z",
      deliveryConfirmation: "Signed by L. Davies (POD-881920)",
      milestonesHistory: [
        {
          milestone: "Received At Shipping Facility",
          location: "Munich Air Freight Hub",
          timestamp: "2026-08-29T10:00:00Z",
          description: "Export packaged and crated.",
          isCompleted: true,
        },
        {
          milestone: "In Transit",
          location: "LH780 Frankfurt -> Singapore -> Auckland",
          timestamp: "2026-08-31T22:00:00Z",
          description: "International flight transit.",
          isCompleted: true,
        },
        {
          milestone: "Arrived in NZ",
          location: "Auckland Cargo Terminal",
          timestamp: "2026-09-05T06:00:00Z",
          description: "Aircraft touched down, cargo released.",
          isCompleted: true,
        },

        {
          milestone: "Out For Delivery",
          location: "Mainfreight Auckland Central",
          timestamp: "2026-09-08T08:30:00Z",
          description: "On courier van for morning delivery.",
          isCompleted: true,
        },
        {
          milestone: "Delivered",
          location: "Precision European, Auckland",
          timestamp: "2026-09-08T14:22:00Z",
          description: "Delivered in full. Signed by L. Davies.",
          isCompleted: true,
        },
      ],
    },
    documents: [],
    internalNotes: [],
    activity: [
      {
        id: "act-115-1",
        timestamp: "2026-09-08T14:22:00Z",
        timeLabel: "02:22 PM",
        title: "Part delivered",
        description: "Delivered to workshop. Ready to close request.",
        actor: "Marcus Thorne",
        type: "shipment",
      },
    ],
    actionRequired: "Part delivered successfully. Awaiting final closure.",
    actionType: "none",
  },

  // ── 9. Request: AutoHub-P-000110 (Status: Completed) ──
  {
    id: "req-000110",
    requestNumber: "AutoHub-P-000110",
    customerId: "cust-02",
    customerName: "SP Motors Ltd",
    contactName: "James Wilson",
    customerEmail: "james.wilson@spmotors.co.nz",
    customerPhone: "+64 21 555 0192",
    vehicle: {
      make: "Honda",
      model: "CR-V",
      year: 2018,
      vin: "RW1-1002914",
      registration: "JDM810",
      engine: "L15B7 (1.5L VTEC Turbo)",
      variant: "Touring AWD",
      transmission: "CVT",
      driveConfig: "AWD",
    },
    part: {
      name: "Genuine Engine Radiator Assembly & Cooling Fan Module",
      partNumber: "19010-5AA-A01",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Front accident repair complete, radiator required to finish build.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[1],
    dateSubmitted: "2026-08-15",
    lastUpdated: "2026-08-30",
    status: "Completed",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 590.0,
    customerResponse: "Accepted",
    customerQuote: {
      id: "quote-110",
      requestId: "req-000110",
      version: 1,
      itemDescription: "OEM Honda Aluminum Core Radiator Assembly.",
      oemNumber: "19010-5AA-A01",
      quantity: 1,
      unitPrice: 510.0,
      subtotal: 510.0,
      airFreightCost: 120, seaFreightCost: 80,
      gstAmount: 76.96,
      totalAmount: 590.0,
      currency: "NZD",
      estimatedTransitDays: 5,
      validUntil: "2026-08-20",
      termsAccepted: true,
    },
    customerQuoteVersions: [],
    supplierQuotations: [],
    payment: {
      id: "pay-110",
      requestId: "req-000110",
      invoiceNumber: "INV-2026-00110",
      amount: 590.0,
      currency: "NZD",
      status: "Paid",
      paymentReference: "AutoHub-P-000110-PAID",
      dueDate: "2026-08-20",
    },
    documents: [],
    internalNotes: [],
    activity: [
      {
        id: "act-110-1",
        timestamp: "2026-08-30T16:00:00Z",
        timeLabel: "04:00 PM",
        title: "Request completed",
        description: "Order completed and archived in Autohub system.",
        actor: "David Vance",
        type: "status",
      },
    ],
    actionRequired: "Order successfully completed and archived",
    actionType: "none",
  },
  // ── 7. Request: AutoHub-P-000188 (Status: Ordered) ──
  {
    id: "req-000188",
    requestNumber: "AutoHub-P-000188",
    customerId: "cust-01",
    customerName: "AutoCare Auckland",
    contactName: "Dave Miller",
    customerEmail: "dave@autocare.co.nz",
    customerPhone: "+64 9 525 1122",
    vehicle: {
      make: "Nissan",
      model: "Navara",
      year: 2020,
      vin: "MNTVC2D23-908123",
      registration: "NVR202",
      engine: "YS23DDTT (2.3L Twin Turbo Diesel)",
      variant: "ST-X 4WD",
      transmission: "7-Speed Automatic",
      driveConfig: "4WD",
    },
    part: {
      name: "Front Driveshaft Assembly (Right)",
      partNumber: "39100-4KH0A",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Heavy clicking on full lock. Requires genuine replacement.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[0],
    dateSubmitted: "2026-09-12",
    lastUpdated: "Today",
    status: "Ordered",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 620.0,
    actionRequired: "Awaiting supplier fulfillment",
    actionType: "view_details",
  },
  // ── 8. Request: AutoHub-P-000199 (Status: Ordered) ──
  {
    id: "req-000199",
    requestNumber: "AutoHub-P-000199",
    customerId: "cust-02",
    customerName: "SP Motors Ltd",
    contactName: "James Wilson",
    customerEmail: "james.wilson@spmotors.co.nz",
    customerPhone: "+64 21 555 0192",
    vehicle: {
      make: "Honda",
      model: "Civic",
      year: 2018,
      vin: "JHMFC1-000912",
      registration: "CVC912",
      engine: "L15B7 (1.5L Turbo)",
      variant: "RS Sedan",
      transmission: "CVT",
      driveConfig: "FWD",
    },
    part: {
      name: "A/C Compressor Assembly",
      partNumber: "38810-5PA-A01",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Compressor clutch failed. Sourcing direct from Japan.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[1],
    dateSubmitted: "2026-09-13",
    lastUpdated: "Today",
    status: "Ordered",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 1250.0,
    actionRequired: "Supplier order confirmed",
    actionType: "view_details",
  },
  // ── 9. Request: AutoHub-P-000200 (Status: Sourcing) ──
  {
    id: "req-000200",
    requestNumber: "AutoHub-P-000200",
    customerId: "cust-03",
    customerName: "Precision European",
    contactName: "Liam Davies",
    customerEmail: "liam@precisioneuro.co.nz",
    customerPhone: "+64 9 377 8899",
    vehicle: {
      make: "BMW",
      model: "3 Series",
      year: 2021,
      vin: "WBA5L3C09L082910",
      registration: "BMW321",
      engine: "B48",
      variant: "320i",
      transmission: "8-Speed Auto",
      driveConfig: "RWD",
    },
    part: {
      name: "Rear Bumper Cover",
      partNumber: "51128068582",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Collision repair.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[2],
    dateSubmitted: "2026-09-15",
    lastUpdated: "Today",
    status: "Sourcing",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 850.0,
    actionRequired: "Sourcing replacement part",
    actionType: "view_details",
  },
  // ── 10. Request: AutoHub-P-000201 (Status: Ready for Dispatch) ──
  {
    id: "req-000201",
    requestNumber: "AutoHub-P-000201",
    customerId: "cust-02",
    customerName: "SP Motors Ltd",
    contactName: "James Wilson",
    customerEmail: "james.wilson@spmotors.co.nz",
    customerPhone: "+64 21 555 0192",
    vehicle: {
      make: "Mazda",
      model: "CX-5",
      year: 2019,
      vin: "KF2P-302198",
      registration: "CX5999",
      engine: "SH-VPTS",
      variant: "AWD",
      transmission: "6-Speed Auto",
      driveConfig: "AWD",
    },
    part: {
      name: "Headlight Assembly (Right)",
      partNumber: "K123-51-031",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Replacement for cracked lens.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SHARED_ADDRESSES[1],
    dateSubmitted: "2026-09-10",
    lastUpdated: "Today",
    status: "Ready for Dispatch",
    assignedStaff: "Sarah Jenkins",
    assignedStaffRole: "Procurement",
    quotedValue: 1050.0,
    actionRequired: "Ready for dispatch",
    actionType: "none",
  }
];

// ─── Centralized Mock Notifications ────────────────────────

export const INITIAL_NOTIFICATIONS: PortalNotification[] = [
  {
    id: "notif-01",
    type: "New Request",
    title: "New Request: AutoHub-P-000145",
    description: "AutoCare Auckland submitted request for Toyota RAV4 Front Brake Rotors.",
    timestamp: "10m ago",
    read: false,
    requestId: "req-000145",
  },
  {
    id: "notif-02",
    type: "Quote Accepted",
    title: "Quote Accepted: AutoHub-P-000123",
    description: "Dave Miller accepted quote for NZ$410.00. Status: Awaiting Payment.",
    timestamp: "45m ago",
    read: false,
    requestId: "req-000123",
  },
  {
    id: "notif-03",
    type: "Payment Received",
    title: "Payment Confirmed: AutoHub-P-000125",
    description: "NZ$640.00 received. Supplier Order unlocked and placed.",
    timestamp: "2h ago",
    read: true,
    requestId: "req-000125",
  },
  {
    id: "notif-04",
    type: "Shipment Updated",
    title: "Shipment In Transit: AutoHub-P-000120",
    description: "Flight JL0711 departed Nagoya. Arriving in NZ this weekend.",
    timestamp: "5h ago",
    read: true,
    requestId: "req-000120",
  },
  {
    id: "notif-05",
    type: "Customer Registration",
    title: "New Trade Application",
    description: "Westside Fleet Services registered. Awaiting admin verification.",
    timestamp: "Yesterday",
    read: true,
  },
];
